sudo: required
language: generic
services:
  - "docker"

before_install:
  -docker build -t sreeraj510105/react-git -f Dockerfile.dev .

script:
  docker run -e CI=true sreeraj510105/react-git npm run test 